import { validateNpcPlacements } from "./mapSpawnValidator.js";

export const NEUTRAL_EMOTION = {
    label: "neutral",
    intensity: 0.18,
    vad: { V: 0, A: 0, D: 0 }
};

export const CHOICES = {
    TALK: { id: "TALK", label: "PRAAT" },
    LISTEN: { id: "LISTEN", label: "LUISTER" },
    ASK: { id: "ASK", label: "VRAAG DOOR" },
    SHARE: { id: "SHARE", label: "DEEL CLUE" },
    PRESS: { id: "PRESS", label: "ZET DRUK" },
    REUNITE: { id: "REUNITE", label: "VERENIG DORP" },
    GOODBYE: { id: "GOODBYE", label: "TOT ZIENS" }
};

const NPC_DEFINITIONS = [
    {
        id: "lyra",
        name: "Lyra",
        title: "Town Nurse",
        map: "town",
        x: 318,
        y: 1186,
        spriteKey: "players",
        spriteFrame: "nurse_front.png",
        clueId: "sleep_hum",
        clueTitle: "Slaaphum",
        clueText: "Lyra heard Sol humming in his sleep about a gate that sings under moonlight.",
        shareNeed: 0,
        revealThreshold: 2,
        pressThreshold: 3,
        speakingStyle: "Gentle, composed, and warm. Speaks like someone steadying a room in crisis.",
        description: "The nurse who keeps Echo Town calm, but she has been carrying everyone's worry alone.",
        opening: "Lyra folds a towel with measured hands. \"The whole town is holding its breath tonight.\"",
        support: "Lyra's shoulders loosen. \"Thank you. Everyone comes to me frightened, and I forgot I was allowed to be frightened too.\"",
        guarded: "\"I want to help, but I can't scatter panic across town. Earn a little trust first.\"",
        pressure: "\"Please don't turn this into a hunt. Sol is scared enough already.\"",
        completion: "\"Hear that? The lantern finally sounds like a lullaby again.\""
    },
    {
        id: "piper",
        name: "Piper",
        title: "Courier",
        map: "town",
        x: 412,
        y: 1188,
        spriteKey: "players",
        spriteFrame: "femaletrainer_front.png",
        clueId: "ribbon_fence",
        clueTitle: "Zilveren Lint",
        clueText: "Piper's courier satchel snagged on the west fence, and a silver ribbon tore free beside it.",
        shareNeed: 0,
        revealThreshold: 2,
        pressThreshold: 2,
        speakingStyle: "Fast, bright, and restless. Her words arrive in nervous bursts.",
        description: "A courier who hides nerves behind speed and jokes. She saw more than she admits at first.",
        opening: "Piper bounces on her heels. \"If I stop moving, I start thinking. Bad trade tonight.\"",
        support: "\"Okay. Deep breath. Right. I can actually remember what I saw if I stop sprinting inside my own head.\"",
        guarded: "\"I know things, sure, but I'm not blurting them into the wind unless I know you're serious.\"",
        pressure: "\"Hey, easy. I already feel guilty enough.\"",
        completion: "\"The whole square is talking again. That's better than silence.\""
    },
    {
        id: "sable",
        name: "Sable",
        title: "Tinker",
        map: "town",
        x: 528,
        y: 1182,
        spriteKey: "players",
        spriteFrame: "boss_front.png",
        clueId: "crate_confession",
        clueTitle: "Kratbekentenis",
        clueText: "Sable hid the Echo Lantern inside a route crate because its whispering frightened Sol.",
        shareNeed: 2,
        revealThreshold: 4,
        pressThreshold: 2,
        speakingStyle: "Low, clipped, defensive, but unexpectedly sincere when cornered by kindness.",
        description: "A mechanic whose instincts are protective, even when his choices look suspicious.",
        opening: "Sable keeps one hand on a wrench. \"People get loud when they don't understand a machine.\"",
        support: "\"...You really came to hear me out? Fine. That's rarer than it should be.\"",
        guarded: "\"Not talking. Not until you bring me something real.\"",
        pressure: "\"Push harder and I shut down. Simple as that.\"",
        completion: "\"Maybe next time I tell the truth before I build a hiding place.\""
    },
    {
        id: "orin",
        name: "Orin",
        title: "Stargazer",
        map: "town",
        x: 176,
        y: 1054,
        spriteKey: "players",
        spriteFrame: "professor_right_walk.002.png",
        clueId: "moon_chorus",
        clueTitle: "Maankoor",
        clueText: "Orin explains that the Lantern mirrors fear; if the town gathers calmly, it will harmonize instead of whisper.",
        shareNeed: 1,
        revealThreshold: 2,
        pressThreshold: 5,
        speakingStyle: "Measured, poetic, and precise. He sounds like he thinks in constellations.",
        description: "The observatory keeper who understands the Echo Lantern better than anyone, but blames himself for its side effects.",
        opening: "Orin watches the sky. \"Every mystery is just a feeling waiting for enough witnesses.\"",
        support: "\"Then perhaps tonight can still become a chorus instead of a warning.\"",
        guarded: "\"Patterns first. Conclusions later.\"",
        pressure: "\"Urgency without clarity is just another storm.\"",
        completion: "\"Listen closely. The Lantern is finally answering hope instead of fear.\""
    },
    {
        id: "bram",
        name: "Bram",
        title: "Route Guard",
        map: "route1",
        x: 418,
        y: 118,
        spriteKey: "players",
        spriteFrame: "knight_back_walk.002.png",
        clueId: "route_dust",
        clueTitle: "Sterstof",
        clueText: "Bram found silver dust and a humming crate on Route 1, just past the gate.",
        shareNeed: 0,
        revealThreshold: 2,
        pressThreshold: 2,
        speakingStyle: "Grounded, spare, direct. He says little, but what he says matters.",
        description: "The route guard who notices details and resents panic more than danger.",
        opening: "Bram scans the road. \"Tracks don't lie. People do.\"",
        support: "\"Good. Someone else is looking at the ground instead of the gossip.\"",
        guarded: "\"You want facts? Bring patience.\"",
        pressure: "\"Bad way to get help. Try again.\"",
        completion: "\"Town sounds different already. Less fear in the air.\""
    },
    {
        id: "mirelle",
        name: "Mirelle",
        title: "Ashveld Nurse",
        map: "ashveld",
        x: 432,
        y: 414,
        spriteKey: "players",
        spriteFrame: "nurse_front.png",
        clueId: "ashveld-heartbeat",
        clueTitle: "Ashveld Hartslag",
        clueText: "Mirelle keeps Ashveld steady by listening for what people refuse to say out loud.",
        shareNeed: 99,
        revealThreshold: 99,
        pressThreshold: 99,
        speakingStyle: "Soft-spoken, observant, and comforting without sounding distant.",
        description: "The Pokecenter nurse in Ashveld who notices stress before anyone else names it.",
        opening: "Mirelle folds a blanket. \"Ashveld sleeps lightly. People here hear every rumor twice.\"",
        support: "\"That's better. Calm voices travel farther than panic.\"",
        guarded: "\"Questions are fine. I just won't turn the center into a rumor mill.\"",
        pressure: "\"This is a place to recover, not to corner people.\"",
        completion: "\"Even the town's heartbeat sounds steadier tonight.\""
    },
    {
        id: "tavi",
        name: "Tavi",
        title: "Ashveld Shopkeep",
        map: "ashveld",
        x: 706,
        y: 446,
        spriteKey: "players",
        spriteFrame: "tuxemartemployee_front.png",
        clueId: "ashveld-ledger",
        clueTitle: "Ashveld Voorraadboek",
        clueText: "Tavi tracks the town by what vanishes from the shelves before storms.",
        shareNeed: 99,
        revealThreshold: 99,
        pressThreshold: 99,
        speakingStyle: "Quick, practical, and a little theatrical when the shop is quiet.",
        description: "Ashveld's Pokemart clerk, equal parts gossip filter and logistics machine.",
        opening: "Tavi taps a ledger. \"If fear goes up, antidotes and ropes disappear first. Towns always tell on themselves.\"",
        support: "\"There we go. A sensible conversation. Much cheaper than a panic.\"",
        guarded: "\"You'll get a cleaner answer if you stop asking like you're auditing me.\"",
        pressure: "\"Push any harder and I start charging consultation fees.\"",
        completion: "\"Trade's back to normal. That's how you know a town forgave the day.\""
    },
    {
        id: "rowan",
        name: "Rowan",
        title: "Ashveld Caretaker",
        map: "ashveld",
        x: 678,
        y: 832,
        spriteKey: "players",
        spriteFrame: "professor_front.png",
        clueId: "ashveld-bells",
        clueTitle: "Ashveld Klokken",
        clueText: "Rowan times his rounds to the old bells because silence unsettles the square.",
        shareNeed: 99,
        revealThreshold: 99,
        pressThreshold: 99,
        speakingStyle: "Measured and reflective, with the patience of someone who works around old things.",
        description: "Caretaker of Ashveld's memorial hall, more interested in preserving calm than spectacle.",
        opening: "Rowan watches the square. \"A town breathes through its pauses. Ashveld has learned not to fear them.\"",
        support: "\"You noticed that too. Most people only hear noise, not rhythm.\"",
        guarded: "\"I don't mind questions. I mind careless ones.\"",
        pressure: "\"Pressure ruins old masonry and good conversation in equal measure.\"",
        completion: "\"The bells sound lighter when people stop bracing for the worst.\""
    },
    {
        id: "selene",
        name: "Selene",
        title: "Gym Guide",
        map: "crysthaven",
        x: 1232,
        y: 574,
        spriteKey: "players",
        spriteFrame: "girl1_front.png",
        clueId: "crysthaven-gymlight",
        clueTitle: "Gymlicht",
        clueText: "Selene says Crysthaven's gym glow is the city's way of refusing to dim itself.",
        shareNeed: 99,
        revealThreshold: 99,
        pressThreshold: 99,
        speakingStyle: "Bright, confident, and encouraging, like someone used to welcoming challengers.",
        description: "A gym guide who treats confidence as something people can borrow until it becomes their own.",
        opening: "Selene grins toward the gym facade. \"Crysthaven likes its challenges visible. No hiding from growth here.\"",
        support: "\"Exactly. Nerves are just unused courage.\"",
        guarded: "\"I can help, but not if you're trying to turn every answer into a shortcut.\"",
        pressure: "\"That attitude won't get you far in a gym or a city.\"",
        completion: "\"Now that's the Crysthaven tempo I like.\""
    },
    {
        id: "corin",
        name: "Corin",
        title: "Canal Fisher",
        map: "crysthaven",
        x: 594,
        y: 702,
        spriteKey: "players",
        spriteFrame: "knight_front.png",
        clueId: "crysthaven-current",
        clueTitle: "Stadsstroom",
        clueText: "Corin measures the city by current and crowd the same way: both drift where space allows.",
        shareNeed: 99,
        revealThreshold: 99,
        pressThreshold: 99,
        speakingStyle: "Blunt, weathered, and surprisingly philosophical in short bursts.",
        description: "A fisher who understands flow, patience, and the value of staying still long enough to notice change.",
        opening: "Corin squints down the street. \"Cities have currents too. Stand still and you'll feel which way people are leaning.\"",
        support: "\"Good. Not every answer needs to splash to matter.\"",
        guarded: "\"You'll hear more if you stop yanking at the line.\"",
        pressure: "\"Rush the pull and the catch tears loose.\"",
        completion: "\"Smooth water, smooth streets. That's enough for me.\""
    },
    {
        id: "mara",
        name: "Mara",
        title: "City Architect",
        map: "crysthaven",
        x: 530,
        y: 1076,
        spriteKey: "players",
        spriteFrame: "omnichannelceo_front.png",
        clueId: "crysthaven-blueprint",
        clueTitle: "Blauwdruk",
        clueText: "Mara says every district needs one place to gather and one place to breathe.",
        shareNeed: 99,
        revealThreshold: 99,
        pressThreshold: 99,
        speakingStyle: "Precise, elegant, and quietly demanding of coherence.",
        description: "The planner behind Crysthaven's layout, always thinking in avenues, sight lines, and mood.",
        opening: "Mara studies the avenue. \"Good cities direct people without making them feel handled.\"",
        support: "\"Yes. Design is just empathy that learned geometry.\"",
        guarded: "\"A useful question deserves a precise answer. An impatient one does not.\"",
        pressure: "\"If you want clarity, stop mistaking force for direction.\"",
        completion: "\"The whole boulevard reads cleaner when people aren't carrying so much tension.\""
    },
    {
        id: "jules",
        name: "Jules",
        title: "Market Runner",
        map: "crysthaven",
        x: 1090,
        y: 1110,
        spriteKey: "players",
        spriteFrame: "red_front.png",
        clueId: "crysthaven-post",
        clueTitle: "Marktpost",
        clueText: "Jules knows every shortcut in Crysthaven and half the stories attached to them.",
        shareNeed: 99,
        revealThreshold: 99,
        pressThreshold: 99,
        speakingStyle: "Energetic, playful, and always one step from running off to the next errand.",
        description: "A courier who turns the city's long avenues into a playground of momentum.",
        opening: "Jules bounces in place. \"If I stop moving, Crysthaven feels twice as big. So I don't stop moving.\"",
        support: "\"There it is. You get the city. Keep pace, don't fight it.\"",
        guarded: "\"I can answer, sure, but not while you're trying to sprint through the conversation.\"",
        pressure: "\"Too much pressure and I just vanish into the next alley.\"",
        completion: "\"That's the city back on its feet. Fast, bright, impossible to pin down.\""
    }
];

export const RESOLVED_NPC_DEFINITIONS = validateNpcPlacements(NPC_DEFINITIONS);
