name = "pokesol-worker"
main = "src/index.js"
compatibility_date = "2024-09-23"

[[durable_objects.bindings]]
name = "MAP_ROOM"
class_name = "MapRoom"

[[durable_objects.bindings]]
name = "PLAYER_STATE"
class_name = "PlayerState"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MapRoom", "PlayerState"]
